<a href="https://colab.research.google.com/github/soph968/deep-learning-coursera/blob/master/Arrays_in_Numpy_common_mistakes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [4]:
print(a)

[-1.41100797  0.72132491 -0.72771963  0.62131623 -1.03437188]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[-1.41100797  0.72132491 -0.72771963  0.62131623 -1.03437188]


In [7]:
print(np.dot(a, a.T))

4.496788040188759


In [8]:
a = np.random.randn(5,1)

In [9]:
print(a)

[[-0.85741189]
 [ 1.26407303]
 [ 1.12906099]
 [ 0.03208793]
 [ 0.18365948]]


In [10]:
print(a.T)

[[-0.85741189  1.26407303  1.12906099  0.03208793  0.18365948]]


In [11]:
print(np.dot(a, a.T))

[[ 7.35155146e-01 -1.08383124e+00 -9.68070317e-01 -2.75125733e-02
  -1.57471825e-01]
 [-1.08383124e+00  1.59788063e+00  1.42721555e+00  4.05614879e-02
   2.32159000e-01]
 [-9.68070317e-01  1.42721555e+00  1.27477872e+00  3.62292309e-02
   2.07362759e-01]
 [-2.75125733e-02  4.05614879e-02  3.62292309e-02  1.02963530e-03
   5.89325279e-03]
 [-1.57471825e-01  2.32159000e-01  2.07362759e-01  5.89325279e-03
   3.37308059e-02]]


In [13]:
a = np.random.randn(2,3)
print(a)

[[-3.20564554 -0.15152375 -1.20376887]
 [ 0.36082515  0.7519627   0.74941292]]


In [15]:
b = np.random.randn(2, 1)
print(b)

[[ 0.56036061]
 [-0.47095772]]


In [16]:
c = a + b

In [17]:
print(c.shape)

(2, 3)


In [18]:
a = np.random.randn(4,3)
print(a)
b = np.random.randn(3, 2)
print(b)

[[ 0.55536792  1.11954679 -0.68873557]
 [ 0.5348175   1.11888811  0.08580075]
 [ 0.39189199  0.69472079  0.79962656]
 [ 0.67618397  0.13755211  0.62632435]]
[[ 1.20479594 -0.9602512 ]
 [ 0.15166128 -0.71791892]
 [ 0.08345991 -0.37988094]]


In [19]:
c = a * b

ValueError: ignored

In [22]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b) 

In [23]:
print(c.shape)

(12288, 45)


In [24]:
 a = np.random.randn(3, 3)
 b = np.random.randn(3, 1)
 c = a*b 

In [25]:
c

array([[ 0.21643727,  0.40827661,  0.47447008],
       [ 0.14918272, -0.02212835, -0.31900937],
       [-0.33716055, -0.32037814, -0.06638643]])